### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by spiderlord202** [nvuillam/node-java-caller#11]
The hosting provider I am using does not allow env variables so I cant set DEBUG and I would like it if you added another way to enable debug and also add a cli.

**Comment by nvuillam** [comment]
what if you add `process.env.debug=*` in your code before calling JavaCaller ?

About a CLI... why not, but I have a big backlog... so maybe you'd like to submit a pull request ? :)

**Comment by spiderlord202** [comment]
Ok. I'll work on a cli in my spare time if I remember

**Comment by nvuillam** [comment]
Great, please let me know if you need support :)
