### ISSUE TITLE
How to differentiate between java options and java arguments?

### ISSUE THREAD

**Issue by hebelsan** [nvuillam/node-java-caller#13]
Hi,

In my project I want to execute a jar in the following way:
**java --add-opens=java.base/java.lang=ALL-UNNAMED -jar ...**
However this seems not possible with your library.
The way arguments are sometimes options and sometimes arguments is also magic to me.
I would prefer an api where you can separately specify java arguments and java options.

Best regards,
Alex

**Comment by hebelsan** [comment]
Another solution for this issue would be to provide the user an api in which he has full power over the java call parameters.

**Comment by hebelsan** [comment]
Hi nvuillam,

Thanks for your quick response!
The way I call the javaCaller is pretty much the same as you suggested:
`const java = new JavaCaller({
	rootPath: __dirname,
	additionalJavaArgs: "--add-opens=java.base/java.lang=ALL-UNNAMED",
	jar: "file.jar",
	minimumJavaVersion: 11,
});`

I looked into the code and I found out that it is completely irrelevant if to specify the parameter as ** additionalJavaArgs** in the JavaCaller constructor or as java.run([...]) parameter because those parameter get concatenated together in the same array anyway (see _java-caller.js_ line 88).
The only differntiation is done in _java-caller.js_ line 188.
If a paramter starts with -X or -D it will be handled as java option.
But in my case I want to specify the parameter as java option without starting with -X or -D so that I can create a call in the format: _java [ options ] -jar filejar [ arguments ]_ ( https://docs.oracle.com/javase/7/docs/technotes/tools/windows/java.html).
I also tried to trick the system by defining my parameter as ["-D --add-opens=java.base/java.lang=ALL-UNNAMED"].
This will place the parameter at the correct position in the java call (before -jar) but doesn't work because it will be translated as one argument (see _java-caller.js_ line 106)

best regards,
Alex

**Comment by nvuillam** [comment]
Please can you try additionalJavaArgs as an array ?

```javascript
const java = new JavaCaller({
	rootPath: __dirname,
	additionalJavaArgs: ["--add-opens=java.base/java.lang=ALL-UNNAMED"],
	jar: "file.jar",
	minimumJavaVersion: 11,
});
```

I could also allow to send a property javaArgs in run() method, so you would be able to call something like:

```javascript
java.run(["your","jar","args"],{javaArgs: ["--add-opens=java.base/java.lang=ALL-UNNAMED"]})
```

**Comment by hebelsan** [comment]
AddditionalJAvaArgs as an array doesn't solve the problem.
I get: 
```
java-caller Java command: java -jar file.jar --add-opens=java.base/java.lang=ALL-UNNAMED
```
and I want:
```
java-caller Java command: java --add-opens=java.base/java.lang=ALL-UNNAMED -jar file.jar
```
Notice the position of my parameter **--add-opens=java.base/java.lang=ALL-UNNAMED**.
This is impossible with the current implementation because only parameters starting with -X or -D it will be handled as java option.

**Comment by nvuillam** [comment]
Got it, I'll provide you a fix ASAP :)

**Comment by nvuillam** [comment]
@hebelsan Released in 2.4.0 :)

https://github.com/nvuillam/node-java-caller/releases/tag/v2.4.0

You can now use additionalJavaArgs in the constructor, or javaArgs in runOptions :)

```javascript
java.run(["your","jar","args"],{javaArgs: ["--add-opens=java.base/java.lang=ALL-UNNAMED"]})
```

Please can you confirm it solves your issue ? thanks !

**Comment by hebelsan** [comment]
Yes, that fixed my issue!
Thank you very much for your fast fix and support!

**Comment by nvuillam** [comment]
You're welcome :)
