### ISSUE TITLE
Getting parameter inside Main method or another class Method

### ISSUE THREAD

**Issue by marceloch2** [nvuillam/node-java-caller#17]
Hi, how can I get the args passed via .run() inside the Main or another method?

I was checking this [issue](https://github.com/nvuillam/node-java-caller/issues/13), and I have tried both but no luck.
Do you have an example on this repo showing it?

Thanks in advance for your time and work on this lib.

**Comment by nvuillam** [comment]
Hi @marceloch2 

You can send that as a string array in the first argument :) you'l lthen be able to retrieve them in your `public static void main()` method

Example:

```
await java.run(["arg1","arg2","arg3","arg4"])
```

**Comment by marceloch2** [comment]
Thanks for your reply @nvuillam, tried it already and have not received it in my main class inside a .tar file.
I'll double-check again, I'm probably doing something wrong, I'll reply and close this issue if I have success.

**Comment by nvuillam** [comment]
a `tar` ? Do you mean `jar` ?

**Comment by nvuillam** [comment]
That's strange, I have same use cases that are working :/

For example this test method:  https://github.com/nvuillam/node-java-caller/blob/76801935ff45f75d2955c69b5c8bea8f889b66b0/test/java-caller.test.js#L75

**Comment by marceloch2** [comment]
Hi @nvuillam It works properly, was an error with our code, thanks for your time and sorry about it.

**Comment by nvuillam** [comment]
@marceloch2 no problem, glad you solved your issue :)
