### ISSUE TITLE
Does not work on M1 Macs

### ISSUE THREAD

**Issue by rubixibuc** [nvuillam/node-java-caller#18]
M1 Macs should be able to run x86 instructions anyway

Unexpected error: Unsupported architecture
Error: Unsupported architecture

**Comment by nvuillam** [comment]
Please can you share the whole error ?

In which context are you using node-java-caller ?

There may be solutions: https://apple.stackexchange.com/a/431576

**Comment by rubixibuc** [comment]
Sure

Java jre or jdk between 8 and 14 is required 
Installing Java jre 14 in /[redacted]/.java-caller...
Unexpected error: Unsupported architecture
Error: Unsupported architecture
    at Object.install (/[redacted]/node_modules/njre/lib/install.js:204:32)
    at JavaCaller.manageJavaInstall (/[redacted]/node_modules/java-caller/lib/java-caller.js:254:43)
    at async JavaCaller.run (/[redacted]/node_modules/java-caller/lib/java-caller.js:86:13)
    at async CodeNarcCaller.startCodeNarcServer (/[redacted]/node_modules/npm-groovy-lint/lib/codenarc-caller.js:262:29)
    at async CodeNarcCaller.callCodeNarcServer (/[redacted]/node_modules/npm-groovy-lint/lib/codenarc-caller.js:98:22)
    at async NpmGroovyLint.callCodeNarc (/[redacted]/node_modules/npm-groovy-lint/lib/groovy-lint.js:235:32)
    at async NpmGroovyLint.run (/[redacted]/node_modules/npm-groovy-lint/lib/groovy-lint.js:65:13)
    at async /[redacted]/node_modules/npm-groovy-lint/lib/index.js:12:9

I am using it with the library: https://github.com/nvuillam/npm-groovy-lint/issues/214

**Comment by direvius** [comment]
Reproduced for me with the same library.

## workaround
- uninstall any Java VMs you have
- install openjdk@11 with brew `brew install openjdk@11`
- make it your default JVM as brew suggests `sudo ln -sfn /opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk`
- I was able to start npm-groovy-lint after that

- it doesn't work if any other JVMs of newer versions (>14) installed. For example, the one from IntelliJ IDEA
- even if you specify java binary directly with the `-j` flag

**Comment by Sickafant** [comment]
> * even if you specify java binary directly with the `-j` flag

For me, being able to use the -j flag would be enough, but I noticed a bug for it so I raised #23 to address that.

**Comment by christopher-francisco** [comment]
I followed @direvius steps, and then I got:

```
Unable to start CodeNarc server: {
  "status": 1,
  "stdout": "",
  "stderr": "",
  "childJavaProcess": {
    "_events": {},
    "_eventsCount": 2,
    "_closesNeeded": 1,
    "_closesGot": 1,
    "connected": false,
    "signalCode": null,
    "exitCode": 1,
    "killed": false,
    "spawnfile": "/usr/bin/java",
    "_handle": null,
    "spawnargs": [
      "/usr/bin/java",
      "-Xms256m",
      "-Xmx2048m",
      "-cp",
      "/Users/me/project/node_modules/.pnpm/npm-groovy-lint@11.1.1/node_modules/npm-groovy-lint/lib/java/CodeNarcServer.jar:/Users/me/project/node_modules/.pnpm/npm-groovy-lint@11.1.1/node_modules/npm-groovy-lint/lib/java/*",
      "com.nvuillam.CodeNarcServer",
      "--server"
    ],
    "pid": 10966,
    "stdin": null,
    "stdout": null,
    "stderr": null,
    "stdio": [null, null, null]
  }
}

["--server"]

npm-groovy-lint results in 0 linted files:
```

**Comment by nvuillam** [comment]
@christopher-francisco please can you share how you call node-java-caller ?

**Comment by nzsimonc** [comment]
v3.3.0 looks to resolve this, so this issue can be closed. 
This is the commit that resolves it https://github.com/nvuillam/node-java-caller/commit/ce4adfe754bdff10c5e4dfd1dc662f7c652eabc5 #50

**Comment by nvuillam** [comment]
Thank for you feedback @nzsimonc :)
