### ISSUE TITLE
in ./node_modules/java-caller/lib/cli.js  Module parse failed: Unexpected character '#' (1:0) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders > #! /usr/bin/env node

### ISSUE THREAD

**Issue by Arvin-J** [nvuillam/node-java-caller#19]
I get build error.

in ./node_modules/java-caller/lib/cli.js

Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #! /usr/bin/env node

**Comment by nvuillam** [comment]
What is your node.js version ?

You can type `node -v` in command line

**Comment by nvuillam** [comment]
If it is a webpack issue, I think there is a solution here -> https://stackoverflow.com/a/50102672/7113625

**Comment by FlyingNoob** [comment]
this can support electron ？

**Comment by nvuillam** [comment]
I have not heard of a use of node-java-caller within electron... but maybe this shebang is not really useful... I'll have a look

**Comment by nvuillam** [comment]
If you still have the issue, please reopen :)
