### ISSUE TITLE
params are not received 

### ISSUE THREAD

**Issue by sKY02644** [nvuillam/node-java-caller#20]
for some reasons params are not been received on some machines after building for production with quasar electron 
please assist.

The error code is 1
and args return as empty

**Comment by nvuillam** [comment]
Do you mean that for the same application ( which is ? ), node-java-caller works on some machines and not others ?

What are the OS of the machines where it works, and of the machines where it does not work ?

**Comment by sKY02644** [comment]
yes for the same application

the args are been sent to the .jar file and some other machines the args come in as empty

all machines are running windows 10 with Java 10

**Comment by sKY02644** [comment]
if i should run the command

java -jar [path to jar file] [path to pdf file] 'arg1' 'arg2' 'arg'

it works on all the machines

**Comment by nvuillam** [comment]
yes but in your js code (i assume you use node-java-caller as module), how to you call the module ?

**Comment by sKY02644** [comment]
> hmmm how to you call node-java-caller in your code ? with a specific java version ? maybe the working machines have admin users, and the not working are not admin ? The choice of Java 10 is strange, usually people use 8 or 11 as "old" versions ^^

so you saying the user needs to be an admin user and the Java version must be either 8 or 11?

**Comment by sKY02644** [comment]
> yes but in your js code (i assume you use node-java-caller as module), how to you call the module ?

 ` const java = new JavaCaller({
    jar: jarFilePath,
    rootPath: path.join(__dirname, "..", "..", "vsky"),
    javaExecutable: "",
  });

  const printType = "print";
  const copies = printOptions?.copies || "1";

  const { status, stdout, stderr } = await java.run([`${padfFilePath}`, `${printType}`, `${copies}`]);

  console.log(`The status code returned by java command is ${status}`);

  if (stdout) {
    console.log("stdout: " + stdout);
  }

  if (stderr) {
    console.log("stderr: " + stderr);
  }`

**Comment by nvuillam** [comment]
and there is nothing in stdout / stderr ?

**Comment by sKY02644** [comment]
> and there is nothing in stdout / stderr ?

there error in the stderr is coming from my check in my Java code for args not equal to 3

**Comment by sKY02644** [comment]
`Integer argsLen = args.length;

        if (!argsLen.equals(3))
        {
            System.err.println("usage: java " + Arrays.toString(args) + " <input>" + " args Length: " + argsLen);
            System.exit(1);
        }`

Java code

**Comment by sKY02644** [comment]
are you opting i use Java version 8 || 10 across all machines?

**Comment by sKY02644** [comment]
hello  so after series of debugging i noticed the something strange

so users with USER NAMES with spaces in them was sending separate arguments

eg.

username => "C:\Users\John Doe\Documents\somefile.pdf"

was been received as => [C:\Users\John,  Doe\Documents\somefile.pdf]

**Comment by sKY02644** [comment]
so on the machines with just single usernames it was showing the correct command but those with multiple names in their usernames e.g. john done othername
had their paths been splitted we had to put an extra " " on the path before it worked

**Comment by nvuillam** [comment]
I'm glad you found a solution to your issue :)
