### ISSUE TITLE
Encoding control

### ISSUE THREAD

**Issue by danunafig** [nvuillam/node-java-caller#25]
Hey,
I guess it would be nice to let users control stdout encoding. As long as spawn cannot have "encdoing" , there is an option to support it with runOptions: 

async run(userArguments, runOptions = {}) {
++runOptions.encoding = runOptions.encoding || 'utf8';
...
child = spawn(javaExe, javaArgs, spawnOptions);
++child.stdout.setEncoding(runOptions.encoding);
...

**Comment by nvuillam** [comment]
Nice idea :)

Would you like to make a pull request ? :)

**Comment by nvuillam** [comment]
Fixed by  #26
