### ISSUE TITLE
JavaCaller is not a constructor

### ISSUE THREAD

**Issue by pdsavard** [nvuillam/node-java-caller#27]
Hi try to follow the instruction for "module" intégration, but I got this error "JavaCaller is not a constructor" on
cont java = new JavaCaller

Any idea?

`const java = new JavaCaller({
        classPath: 'java/JavaCallerTester.jar', // CLASSPATH referencing the package embedded jar files
        mainClass: 'com.nvuillam.javacaller.JavaCallerTester',// Main class to call, must be available from CLASSPATH,
        rootPath: __dirname,
        minimumJavaVersion: 10
    });
    const { status, stdout, stderr } = await java.run(['-a', 'list', '--of', 'arguments']);

    console.log(`The status code returned by java command is ${status}`);
    if (stdout) {
        console.log('stdout of the java command is :\n' + stdout);
    }
    if (stderr) {
        console.log('stderr of the java command is :\n' + stderr);
    }
`

**Comment by VensGTH** [comment]
just change `const JavaCaller  = require('java-caller');` to `const { JavaCaller } = require('java-caller');`

**Comment by nvuillam** [comment]
thank you @VensGTH :)
