### ISSUE TITLE
Flaky `getJavaVersion` logic prevents detection of system installed version of Java

### ISSUE THREAD

**Issue by NecroKote** [nvuillam/node-java-caller#41]
Hi, thanks for the great tool! 

## Context:
- Coming here from VSCodes `vscode-groovy-lint` and `npm-groovy-lint`.
- This issue for me was a direct cause of #18 (but on a M2 mac).

## Issue:
I have a Java@17 installed via `brew` on M2 Mac. `vscode-groovy-lint` fails to lint complaining that it can't install Java 17.
Logs referenced same issue as in #18 ("Unsupported architecture") so I dig deeper trying to ask question:
- "why does it din't pick up system java?". 

This call here https://github.com/nvuillam/node-java-caller/blob/master/lib/java-caller.js#L216 return weird version that fails check at the next line - "17.09".

> % java -version
openjdk version "17.0.9" 2023-10-17
OpenJDK Runtime Environment Homebrew (build 17.0.9+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.9+0, mixed mode, sharing)

## Hacky workaround
I overcome  the issue by doing a "semver"-based hack:
```java
const semver = require("semver");
//...
async getJavaVersion() {
    try {
        const { stderr } = await execPromise("java -version");
        const match = /version "(.*?)"/.exec(stderr);
        const versionNb = match.split("_")[0]; // got rid of any possible stuff after _
        return versionNb;
    } catch (e) {
        debug(`Java not found: ${e.message}`);
        return false;
    }
}

async manageJavaInstall() {
//...
    const javaVersion = await this.getJavaVersion();
// replacing line 217 with this down below
    if (javaVersion === false) return;
    
    const isGt = semver.gt(javaVersion, `${this.minimumJavaVersion}.0.0`)
    const isLt = semver.lt(javaVersion, `${this.maximumJavaVersion || "999"}.0.0`)
    const isValid = isGt && isLt
    console.log('isValid', isValid, isGt, isLt)
    if (!isValid) return;
//...
}
```

If I may, I'd like to suggest adding tests for version parsing and switching logic to compare versions from simple number-based comparison to something more "semver"-like.

**Comment by nvuillam** [comment]
@NecroKote very good suggestion, would you like to make a pull request ? :)

**Comment by NecroKote** [comment]
You bet ;)
