### ISSUE TITLE
Option to use javaw.exe instead of java.exe

### ISSUE THREAD

**Issue by SotirisVas** [nvuillam/node-java-caller#65]
Hi, as the title says, I'd like to ask if theres a way to use the options to call the javaw.exe thats located in the same location as the java.exe in the jdk, but without having to specify the entire path manually. Thanks

**Comment by nvuillam** [comment]
@SotirisVas it's not possible today, but if you want to make a PR that would allow [javaExecutable option](https://github.com/nvuillam/node-java-caller/blob/3292af60ef2ffe56f65ed8a79d4b9c54938fd621/lib/java-caller.js#L47) to be "javaw.exe", i'll accept the PR :)

**Comment by SotirisVas** [comment]
Done, thought of calling it windowless as it might make it more to the point as some might not be entirely familiar with javaw and what it does.

**Comment by nvuillam** [comment]
@SotirisVas released in 3.3.0 :) https://github.com/nvuillam/node-java-caller/releases/tag/v3.3.0
